# Generated by Django 5.2.3 on 2025-06-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_address_intern_address_manager_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intern',
            name='address',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='address',
        ),
    ]
